#!/bin/bash
# =============================================================================
# lib/common.sh — Shared utilities for arch-deploy
# =============================================================================

set -euo pipefail

# Colors
if [[ -t 2 ]]; then
  C_RED='\033[0;31m'
  C_GREEN='\033[0;32m'
  C_YELLOW='\033[1;33m'
  C_BLUE='\033[0;34m'
  C_CYAN='\033[0;36m'
  C_RESET='\033[0m'
else
  C_RED='' C_GREEN='' C_YELLOW='' C_BLUE='' C_CYAN='' C_RESET=''
fi

# ---------------------------------------------------------------------------
# File logging — one file per run, appended
# ---------------------------------------------------------------------------
LOG_DIR="${ARCH_DEPLOY_LOG_DIR:-./logs}"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/deploy.log"

# Rotate if > 5MB
if [[ -f "$LOG_FILE" ]]; then
  log_size=$(stat -c%s "$LOG_FILE")
  if [[ "$log_size" -gt 5242880 ]]; then
    mv "$LOG_FILE" "$LOG_FILE.old"
  fi
fi

log()       { echo -e "${C_CYAN}[arch-deploy]${C_RESET} $*" | tee -a "$LOG_FILE" >&2; }
log_info()  { echo -e "${C_BLUE}[INFO]${C_RESET} $*" | tee -a "$LOG_FILE" >&2; }
log_ok()    { echo -e "${C_GREEN}[OK]${C_RESET} $*" | tee -a "$LOG_FILE" >&2; }
log_warn()  { echo -e "${C_YELLOW}[WARN]${C_RESET} $*" | tee -a "$LOG_FILE" >&2; }
log_err()   { echo -e "${C_RED}[ERR]${C_RESET} $*" | tee -a "$LOG_FILE" >&2; }

# ---------------------------------------------------------------------------
# Fatal error
# ---------------------------------------------------------------------------
die() {
  log_err "$*"
  echo "Log: $LOG_FILE" >&2
  exit 1
}

# ---------------------------------------------------------------------------
# Usage banner (stages should override if they want)
# ---------------------------------------------------------------------------
usage() {
  cat <<'EOF'
arch-deploy — ASUS Zenbook 14 Reinstall Pipeline

Usage:
  ./arch-deploy.sh [global-opts] <stage> [stage-opts]

Global Options:
  --profile PATH   Path to profile YAML (required for most stages)
  --dry-run        Show what would be done; do not modify anything
  --help           Show this help

Stages:
  inspect          Deep system scan on current host
  generate-profile Build machine profile from inspect data
  validate         RO security audit from USB
  prepare          ISO env setup (network, mounts)
  execute          Base installation (subvol-reset, pacstrap, GRUB)
  configure        Post-install (AUR, dotfiles, services)
  verify           Seal and verify new system

Examples:
  ./arch-deploy.sh inspect
  ./arch-deploy.sh --profile profiles/my-machine.yaml prepare --dry-run
  ./arch-deploy.sh --profile profiles/my-machine.yaml execute
EOF
}

# ---------------------------------------------------------------------------
# Dry-run guard
# ---------------------------------------------------------------------------
DRY_RUN="${ARCH_DEPLOY_DRY_RUN:-false}"

run() {
  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${C_YELLOW}[DRY-RUN]${C_RESET} $*"
  else
    log_info "EXEC: $*"
    "$@"
  fi
}

run_shell() {
  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${C_YELLOW}[DRY-RUN]${C_RESET} $1"
  else
    log_info "EXEC: $1"
    bash -c "$1"
  fi
}

# ---------------------------------------------------------------------------
# Confirmations
# ---------------------------------------------------------------------------
confirm() {
  local msg="${1:-Continue?}"
  local ans
  read -rp "$msg [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]] || die "Aborted by user."
}

confirm_critical() {
  local msg="${1:-This is a DESTRUCTIVE operation.}"
  echo -e "${C_RED}═══════════════════════════════════════════════════════════════${C_RESET}"
  echo -e "${C_RED}  $msg${C_RESET}"
  echo -e "${C_RED}═══════════════════════════════════════════════════════════════${C_RESET}"
  local ans
  read -rp "Type 'yes' to proceed: " ans
  [[ "$ans" == "yes" ]] || die "Aborted by user."
}

# ---------------------------------------------------------------------------
# Requirements
# ---------------------------------------------------------------------------
require_root() {
  [[ $EUID -eq 0 ]] || die "This stage must be run as root."
}

require_command() {
  local cmd_path
  cmd_path=$(command -v "$1")
  [[ -n "$cmd_path" ]] || die "Required command not found: $1"
}

# ---------------------------------------------------------------------------
# Profile accessors (flat env vars generated by 02-generate-profile)
# ---------------------------------------------------------------------------
profile_get() {
  local key="$1"
  local var="PROFILE_${key//./__}"
  var="${var//-/_}"
  printf '%s' "${!var:-}"
}

profile_get_or_die() {
  local val
  val=$(profile_get "$1")
  [[ -n "$val" ]] || die "Profile key missing: $1"
  printf '%s' "$val"
}
