#!/bin/bash
# =============================================================================
# lib/disk.sh — Disk and mount helpers
# =============================================================================

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# ---------------------------------------------------------------------------
# Verify we are in UEFI mode
# ---------------------------------------------------------------------------
verify_uefi() {
  if [[ ! -d /sys/firmware/efi ]]; then
    die "Not in UEFI mode. This script is designed for UEFI only."
  fi
  log_ok "UEFI mode confirmed."
}

# ---------------------------------------------------------------------------
# Verify a block device exists
# ---------------------------------------------------------------------------
verify_disk() {
  local disk="$1"
  [[ -b "$disk" ]] || die "Block device not found: $disk"
  log_ok "Disk found: $disk"
}

# ---------------------------------------------------------------------------
# Mount subvolumes per profile
# ---------------------------------------------------------------------------
mount_subvols() {
  local root_dev
  root_dev=$(profile_get_or_die "storage.partitions.root_pool.device")

  local mnt="${1:-/mnt}"

  # Collect subvolume definitions from profile env vars
  # They look like: PROFILE_storage__partitions__root_pool__subvolumes__0__name
  # We iterate by index

  local i=0
  while true; do
    local name_var="PROFILE_storage__partitions__root_pool__subvolumes__${i}__name"
    local name="${!name_var:-}"
    [[ -n "$name" ]] || break

    local mount_var="PROFILE_storage__partitions__root_pool__subvolumes__${i}__mount"
    local mpoint="${!mount_var:-}"

    local opts_var="PROFILE_storage__partitions__root_pool__subvolumes__${i}__options"
    local extra_opts="${!opts_var:-}"

    local target="$mnt$mpoint"
    local opts="rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=${name}"
    [[ -n "$extra_opts" ]] && opts="${opts},${extra_opts}"

    run mkdir -p "$target"
    run mount -o "$opts" "$root_dev" "$target"

    ((i++))
  done

  # Mount EFI
  local efi_dev
  efi_dev=$(profile_get_or_die "storage.partitions.efi.device")
  local efi_mpoint
  efi_mpoint=$(profile_get_or_die "storage.partitions.efi.mount")
  local efi_target="$mnt$efi_mpoint"
  run mkdir -p "$efi_target"
  run mount -o rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro "$efi_dev" "$efi_target"
}

# ---------------------------------------------------------------------------
# Generate fstab from profile
# ---------------------------------------------------------------------------
generate_fstab() {
  local mnt="${1:-/mnt}"
  local fstab="$mnt/etc/fstab"

  local root_dev
  root_dev=$(profile_get_or_die "storage.partitions.root_pool.device")
  local root_uuid
  root_uuid=$(blkid -s UUID -o value "$root_dev")
  [[ -n "$root_uuid" ]] || die "Could not determine UUID of $root_dev"

  local efi_dev
  efi_dev=$(profile_get_or_die "storage.partitions.efi.device")
  local efi_uuid
  efi_uuid=$(blkid -s UUID -o value "$efi_dev")

  run mkdir -p "$(dirname "$fstab")"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "[DRY-RUN] Would write $fstab"
    return 0
  fi

  cat > "$fstab" <<EOF
# Static information about the filesystems.
# Generated by arch-deploy

# BTRFS root pool
UUID=${root_uuid}  /        btrfs  rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/@      0 0
UUID=${root_uuid}  /home    btrfs  rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/@home  0 0
UUID=${root_uuid}  /.swap   btrfs  rw,relatime,nodatacow,compress=no,subvol=/@swap                               0 0
UUID=${root_uuid}  /.snapshots btrfs rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/@snapshots 0 0

# EFI partition
UUID=${efi_uuid}   /efi     vfat   rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro  0 2

# Swapfile
/.swap/swapfile    none     swap   defaults  0 0
EOF

  log_ok "Generated $fstab"
}
