#!/bin/bash
# =============================================================================
# lib/profile.sh — Profile loading helpers
# =============================================================================

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# We rely on the .env file generated by 02-generate-profile.sh.
# This file is pure bash and can be sourced directly.
# If .env is missing, we try to auto-generate it from the YAML using python3
# or yq, so profiles work even on the Arch ISO where python3 may not be installed.

profile_generate_env() {
  local yaml_file="$1"
  local env_file="$2"

  log_info "Attempting to generate .env from YAML..."

  # Prefer python3 + PyYAML (exact same logic as 02-generate-profile.sh)
  if command -v python3 &>/dev/null && python3 -c "import yaml" &>/dev/null; then
    python3 - "$yaml_file" "$env_file" <<'PYEOF'
import sys, yaml

def flatten(d, parent_key='', sep='__'):
    items = []
    if isinstance(d, list):
        for i, v in enumerate(d):
            items.extend(flatten(v, f"{parent_key}{sep}{i}", sep))
    elif isinstance(d, dict):
        for k, v in d.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else k
            items.extend(flatten(v, new_key, sep))
    else:
        items.append((parent_key, str(d)))
    return items

with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)

with open(sys.argv[2], 'w') as out:
    out.write("# Auto-generated from profile YAML. Do not edit manually.\n")
    out.write(f"# Source: {sys.argv[1]}\n\n")
    for k, v in flatten(data):
        safe_k = k.replace('-', '_').replace('.', '_')
        safe_v = v.replace('"', '\\"')
        out.write(f'PROFILE_{safe_k}="{safe_v}"\n')
PYEOF
    log_ok "Generated .env via python3: $env_file"
    return 0
  fi

  # Fallback: yq (if installed)
  if command -v yq &>/dev/null; then
    yq -o=props "$yaml_file" > "$env_file"
    log_ok "Generated .env via yq: $env_file"
    return 0
  fi

  return 1
}

profile_load() {
  local yaml_file="${1:-$PROFILE}"
  [[ -f "$yaml_file" ]] || die "Profile not found: $yaml_file"

  local env_file="${yaml_file%.yaml}.env"
  if [[ ! -f "$env_file" ]]; then
    log_warn "Companion .env not found: $env_file"
    if ! profile_generate_env "$yaml_file" "$env_file"; then
      log_err "Cannot auto-generate .env: python3+PyYAML or yq is required."
      log_err "Options:"
      log_err "  1. Install python3 and PyYAML on the ISO: pacman -S python python-yaml"
      log_err "  2. Or copy a pre-generated .env file next to your .yaml profile"
      die "Cannot load profile without .env file."
    fi
  fi

  # shellcheck source=/dev/null
  source "$env_file"
  log_ok "Loaded profile: $yaml_file"
}
