#!/bin/bash
# =============================================================================
# lib/profile.sh — Profile loading helpers
# =============================================================================

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# We rely on the .env file generated by 02-generate-profile.sh.
# This file is pure bash and can be sourced directly.

profile_load() {
  local yaml_file="${1:-$PROFILE}"
  [[ -f "$yaml_file" ]] || die "Profile not found: $yaml_file"

  local env_file="${yaml_file%.yaml}.env"
  if [[ ! -f "$env_file" ]]; then
    log_warn "Companion .env not found: $env_file"
    log_warn "Run 'generate-profile' stage first, or ensure .env is present."
    die "Cannot load profile without .env file."
  fi

  # shellcheck source=/dev/null
  source "$env_file"
  log_ok "Loaded profile: $yaml_file"
}
